In [1]:
#Importanod librerias
import pandas as pd
import numpy as np
from numpy import matrix, linalg

# 1)

In [2]:
#Definiendo la matriz con los coeficientes de las ecuaciones
A=np.array([[3,2,-1],[3,-2,0],[3,2,1],[3,-2,0],[3,2,-1]])
A

array([[ 3,  2, -1],
       [ 3, -2,  0],
       [ 3,  2,  1],
       [ 3, -2,  0],
       [ 3,  2, -1]])

In [3]:
A_v1=np.array([[3,3,3,3,3]])
A_v1

array([[3, 3, 3, 3, 3]])

In [4]:
A_v2=np.array([[2,-2,2,-2,2]])
A_v2

array([[ 2, -2,  2, -2,  2]])

In [5]:
A_v3= A[:, 2]
A_v3

array([-1,  0,  1,  0, -1])

In [6]:
norm_A_v1=np.linalg.norm(A_v1,ord=2)
norm_A_v1

6.708203932499369

In [7]:
norm_A_v2=np.linalg.norm(A_v2,ord=2)
norm_A_v2

4.47213595499958

In [8]:
norm_A_v3=np.linalg.norm(A_v3,ord=2)
norm_A_v3

1.7320508075688772

In [9]:
q1=A_v1/norm_A_v1
q1

array([[0.4472136, 0.4472136, 0.4472136, 0.4472136, 0.4472136]])

In [10]:
w2=A_v2-(A_v2@np.transpose(q1))@(q1)
w2

array([[ 1.6, -2.4,  1.6, -2.4,  1.6]])

In [11]:
q2=w2/np.linalg.norm(w2,ord=2)
q2

array([[ 0.36514837, -0.54772256,  0.36514837, -0.54772256,  0.36514837]])

In [12]:
w3=A_v3-(A_v3@np.transpose(q1))@q1-(A_v3@np.transpose(q2))@q2
w3

array([-6.66666667e-01, -5.55111512e-17,  1.33333333e+00, -5.55111512e-17,
       -6.66666667e-01])

In [13]:
q3=w3/np.linalg.norm(w3,ord=2)
q3

array([-4.08248290e-01, -3.39934989e-17,  8.16496581e-01, -3.39934989e-17,
       -4.08248290e-01])

In [14]:
a11=np.array(norm_A_v1)
a12=np.array(A_v2@np.transpose(q1))[0,0]
a13=np.array(A_v3@np.transpose(q1))[0]
a21=0
a22=np.array(norm_A_v2)
a23=np.array(A_v3@np.transpose(q2))[0]
a31=0
a32=0
a33=np.array(norm_A_v3)

r=np.array([[a11,a12,a13],
           [a21,a22,a23],
           [a31,a32,a33]])
r

array([[ 6.70820393,  0.89442719, -0.4472136 ],
       [ 0.        ,  4.47213595, -0.36514837],
       [ 0.        ,  0.        ,  1.73205081]])

In [15]:
import numpy as np

def gram_schmidt(A):
    # Get the number of columns in A
    
    A = A.astype(float)
    num_columns = A.shape[1]
    
    # Initialize matrices Q and R with zeros
    Q = np.zeros_like(A, dtype=float)
    R = np.zeros((num_columns, num_columns), dtype=float)
    
    for j in range(num_columns):
        v = A[:, j]  # Get the j-th column of A
        
        for i in range(j):
            # Compute the projection of v onto Q[:, i] and subtract it from v
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        
        # Normalize v to get the i-th column of Q
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    
    return Q, R

A=np.array([[3,2,-1],[3,-2,0],[3,2,1],[3,-2,0],[3,2,-1]])

Q, R = gram_schmidt(A)
print("Q (orthogonalized matrix):\n", Q)
print("R (upper triangular matrix):\n", R)


Q (orthogonalized matrix):
 [[ 0.4472136   0.36514837 -0.40824829]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837  0.81649658]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837 -0.40824829]]
R (upper triangular matrix):
 [[ 6.70820393  0.89442719 -0.4472136 ]
 [ 0.          4.38178046 -0.36514837]
 [ 0.          0.          1.63299316]]


# 2)

In [17]:
#Leyendo datos
df=pd.read_csv("data/bodyfat.csv")
df=df[["BodyFat","Weight","Height","Abdomen"]]
df.head()

BodyFat  Weight  Height  Abdomen
0     12.3  154.25   67.75     85.2
1      6.1  173.25   72.25     83.0
2     25.3  154.00   66.25     87.9
3     10.4  184.75   72.25     86.4
4     28.7  184.25   71.25    100.0

In [21]:
X=df.drop("BodyFat",axis=1)
X["Intercept"]=1
X=X[["Intercept","Weight","Height","Abdomen"]]
X


Intercept  Weight  Height  Abdomen
0            1  154.25   67.75     85.2
1            1  173.25   72.25     83.0
2            1  154.00   66.25     87.9
3            1  184.75   72.25     86.4
4            1  184.25   71.25    100.0
..         ...     ...     ...      ...
247          1  134.25   67.00     83.6
248          1  201.00   69.75    105.0
249          1  186.75   66.00    111.5
250          1  190.75   70.50    101.3
251          1  207.50   70.00    108.5

[252 rows x 4 columns]

In [22]:
y=df[["BodyFat"]]
y

BodyFat
0       12.3
1        6.1
2       25.3
3       10.4
4       28.7
..       ...
247     11.0
248     33.6
249     29.3
250     26.0
251     31.9

[252 rows x 1 columns]