# 2. Ortogonalización Grahm-Schmidt

## 2.1. Función manual para QR vs función `scipy.linalg.qr`

### Importando librerías

In [1]:
#Importanod librerias
import pandas as pd
import numpy as np
from numpy import matrix, linalg
import scipy

### Definiendo Matriz Manual

In [2]:
#Definiendo la matriz con los coeficientes de las ecuaciones
A=np.array([[3,2,-1],[3,-2,0],[3,2,1],[3,-2,0],[3,2,-1]])
A

array([[ 3,  2, -1],
       [ 3, -2,  0],
       [ 3,  2,  1],
       [ 3, -2,  0],
       [ 3,  2, -1]])

### Definiendo algoritmo para hallar QR

In [3]:
def gram_schmidt(A):
    # Get the number of columns in A
    
    A = A.astype(float)
    num_columns = A.shape[1]
    
    # Initialize matrices Q and R with zeros
    Q = np.zeros_like(A, dtype=float)
    R = np.zeros((num_columns, num_columns), dtype=float)
    
    for j in range(num_columns):
        v = A[:, j]  # Get the j-th column of A
        
        for i in range(j):
            # Compute the projection of v onto Q[:, i] and subtract it from v
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        
        # Normalize v to get the i-th column of Q
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    
    return Q, R

#### Ejecutando función

In [4]:
Q, R = gram_schmidt(A)
print("Q (orthogonalized matrix):\n", Q)
print("\nR (upper triangular matrix):\n", R)

Q (orthogonalized matrix):
 [[ 0.4472136   0.36514837 -0.40824829]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837  0.81649658]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837 -0.40824829]]

R (upper triangular matrix):
 [[ 6.70820393  0.89442719 -0.4472136 ]
 [ 0.          4.38178046 -0.36514837]
 [ 0.          0.          1.63299316]]


#### Verificando que QT*Q = I

In [11]:
(Q.T@Q).round()

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])

#### Hallando A multiplicando Q y R

In [19]:
A_cal=Q@R
A_cal.round()

array([[ 3.,  2., -1.],
       [ 3., -2., -0.],
       [ 3.,  2.,  1.],
       [ 3., -2., -0.],
       [ 3.,  2., -1.]])

### Comparando los resultados con la función `scipy.linalg.qr`

#### Hallando Q y R

In [16]:
Q_s,R_s=scipy.linalg.qr(A)
print("Q (orthogonalized matrix):\n", Q_s)
print("\nR (upper triangular matrix):\n", R_s)

Q (orthogonalized matrix):
 [[-4.47213595e-01  3.65148372e-01  4.08248290e-01 -8.61535451e-02
  -7.01838704e-01]
 [-4.47213595e-01 -5.47722558e-01 -5.55111512e-17 -7.01838704e-01
   8.61535451e-02]
 [-4.47213595e-01  3.65148372e-01 -8.16496581e-01 -3.46944695e-18
   2.77555756e-17]
 [-4.47213595e-01 -5.47722558e-01 -2.77555756e-17  7.01838704e-01
  -8.61535451e-02]
 [-4.47213595e-01  3.65148372e-01  4.08248290e-01  8.61535451e-02
   7.01838704e-01]]

R (upper triangular matrix):
 [[-6.70820393 -0.89442719  0.4472136 ]
 [ 0.          4.38178046 -0.36514837]
 [ 0.          0.         -1.63299316]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


#### Verificando que Q es ortogonal

In [18]:
(Q_s.T@Q_s).round()

array([[ 1.,  0.,  0.,  0., -0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [-0.,  0.,  0.,  0.,  1.]])

#### Calculando A con Q y R

In [21]:
A_cal_s=Q_s@R_s
A_cal_s.round()

array([[ 3.,  2., -1.],
       [ 3., -2.,  0.],
       [ 3.,  2.,  1.],
       [ 3., -2.,  0.],
       [ 3.,  2., -1.]])

### Observación QR manual vs QR de Scipy:

#### Se puede notar que para algunas observaciones de las matrices Q y R, los signos cambian dependiendo de la metodología utilizada. También es evidente que usando la función `scipy.linalg.qr` arroja una matriz **Q de tamaño mxm** y **R arroja una matriz de tamaño mxn**, por otra parte, utilizando la `función manual`, se encuentra una matriz **Q de tamaño mxn** y una matriz **R de tamaño nxn**. 

#### Sin embargo, bajo ambas metodologías, se cumple que Q es ortogonal y el cálculo de A multiplicando Q*R da el mismo resultado.

## 2.1. ¿Qué pasa con la factorización QR cuando las columnas son linealmente dependientes?

In [22]:
matriz_dependiente = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9],
    [4, 8, 12]
])

matriz_dependiente

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [31]:
Q, R = gram_schmidt(matriz_dependiente)
print("Q (orthogonalized matrix):\n", Q)
print("\nR (upper triangular matrix):\n", R)

Q (orthogonalized matrix):
 [[0.18257419 0.16439899        nan]
 [0.36514837 0.32879797        nan]
 [0.54772256 0.65759595        nan]
 [0.73029674 0.65759595        nan]]

R (upper triangular matrix):
 [[5.47722558e+00 1.09544512e+01 1.64316767e+01]
 [0.00000000e+00 2.70128921e-15 5.40257841e-15]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]


/tmp/ipykernel_4808/3194432237.py:21: RuntimeWarning: invalid value encountered in divide
  Q[:, j] = v / R[j, j]


In [30]:
(Q.T@Q).round()

array([[ 1.,  1., nan],
       [ 1.,  1., nan],
       [nan, nan, nan]])

In [27]:
Q@R

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

#### Cuando la matriz es linealmente dependiente sucede lo siguiente:

1) La matriz ortogonal (Q) deja de ser ortogonal, dado que QT@Q no da igual a la matriz identidad. Por lo tanto, es una matriz que no minimiza el error.

2) La Matriz R tiene almenos una fila con ceros, esto se debe a que las columnas de A son combinaciones de otras columnas, es decir, tienen la misma dirección pero con diferente longitud.

3) Los puntos anteriores causan que Q@R no den como resultado la matriz A original, porque al no ser ortogonal Q, el sistema no tiene única solución.

## 2.3. Condiciónes para que la factorización QR sea única.

1) Este proceso obtiene matrices Q y R únicas cuando la matriz es cuadrada y no es linealmente dependiente.  Si la matriz no es cuadrada, se pueden hallar multiples Q y R que multiplicadas den como resultado la Matriz A.

2) La factorización QR también es única cuando la matriz es de rango completo, es decir, el número de columnas linealmente independientes igual al número de filas. Esto es otra forma de ver el punto anterior.

# 2)

In [ ]:
#Leyendo datos
df=pd.read_csv("data/bodyfat.csv")
df=df[["BodyFat","Weight","Height","Abdomen"]]
df.head()

BodyFat  Weight  Height  Abdomen
0     12.3  154.25   67.75     85.2
1      6.1  173.25   72.25     83.0
2     25.3  154.00   66.25     87.9
3     10.4  184.75   72.25     86.4
4     28.7  184.25   71.25    100.0

In [ ]:
X=df.drop("BodyFat",axis=1)
X["Intercept"]=1
X=X[["Intercept","Weight","Height","Abdomen"]]
X


Intercept  Weight  Height  Abdomen
0            1  154.25   67.75     85.2
1            1  173.25   72.25     83.0
2            1  154.00   66.25     87.9
3            1  184.75   72.25     86.4
4            1  184.25   71.25    100.0
..         ...     ...     ...      ...
247          1  134.25   67.00     83.6
248          1  201.00   69.75    105.0
249          1  186.75   66.00    111.5
250          1  190.75   70.50    101.3
251          1  207.50   70.00    108.5

[252 rows x 4 columns]

In [ ]:
X_matrix=X.values
X_matrix

array([[  1.  , 154.25,  67.75,  85.2 ],
       [  1.  , 173.25,  72.25,  83.  ],
       [  1.  , 154.  ,  66.25,  87.9 ],
       ...,
       [  1.  , 186.75,  66.  , 111.5 ],
       [  1.  , 190.75,  70.5 , 101.3 ],
       [  1.  , 207.5 ,  70.  , 108.5 ]])

In [ ]:
var_i=X_matrix[:,0]
var_1=X_matrix[:,1]
var_2=X_matrix[:,2]
var_3=X_matrix[:,3]

In [ ]:
y=df[["BodyFat"]].values
y

array([[12.3],
       [ 6.1],
       [25.3],
       [10.4],
       [28.7],
       [20.9],
       [19.2],
       [12.4],
       [ 4.1],
       [11.7],
       [ 7.1],
       [ 7.8],
       [20.8],
       [21.2],
       [22.1],
       [20.9],
       [29. ],
       [22.9],
       [16. ],
       [16.5],
       [19.1],
       [15.2],
       [15.6],
       [17.7],
       [14. ],
       [ 3.7],
       [ 7.9],
       [22.9],
       [ 3.7],
       [ 8.8],
       [11.9],
       [ 5.7],
       [11.8],
       [21.3],
       [32.3],
       [40.1],
       [24.2],
       [28.4],
       [35.2],
       [32.6],
       [34.5],
       [32.9],
       [31.6],
       [32. ],
       [ 7.7],
       [13.9],
       [10.8],
       [ 5.6],
       [13.6],
       [ 4. ],
       [10.2],
       [ 6.6],
       [ 8. ],
       [ 6.3],
       [ 3.9],
       [22.6],
       [20.4],
       [28. ],
       [31.5],
       [24.6],
       [26.1],
       [29.8],
       [30.7],
       [25.8],
       [32.3],
       [30. ],
       [21