# Ejemplo Diagonalización

In [1]:
import numpy as np

In [4]:
A=np.array([[1,-1,1],
           [-2,4,-8],
           [2,4,8]])
A

array([[ 1, -1,  1],
       [-2,  4, -8],
       [ 2,  4,  8]])

In [5]:
np.linalg.eigvals(A)

array([0.76648985+0.j        , 6.11675508+5.02080133j,
       6.11675508-5.02080133j])

In [6]:
eigenvalues,eigenvectors=np.linalg.eig(A)

In [11]:
eigenvalues

array([0.76648985+0.j        , 6.11675508+5.02080133j,
       6.11675508-5.02080133j])

In [12]:
print(eigenvectors)

[[ 0.96719564+0.j          0.15043052-0.04512542j  0.15043052+0.04512542j]
 [-0.02676839+0.j         -0.81756612+0.j         -0.81756612-0.j        ]
 [-0.25261839+0.j          0.17871578+0.52438599j  0.17871578-0.52438599j]]


In [18]:
A@eigenvectors[:,1]

array([ 1.14671241+0.47926057j, -5.00085172-4.10483707j,
       -1.53967725+4.10483707j])

In [19]:
eigenvalues[1]*eigenvectors[:,1]

array([ 1.14671241+0.47926057j, -5.00085172-4.10483707j,
       -1.53967725+4.10483707j])

In [20]:
V=eigenvectors

In [22]:
VI=np.linalg.inv(V)

In [23]:
D=np.diag(eigenvalues)

In [26]:
(V@D@VI).round()

array([[ 1.+0.j, -1.+0.j,  1.-0.j],
       [-2.+0.j,  4.+0.j, -8.+0.j],
       [ 2.+0.j,  4.-0.j,  8.+0.j]])

In [25]:
A

array([[ 1, -1,  1],
       [-2,  4, -8],
       [ 2,  4,  8]])

In [27]:
B=np.array([[1,-2,2],
           [-2,4,4],
           [2,4,8]])

B

array([[ 1, -2,  2],
       [-2,  4,  4],
       [ 2,  4,  8]])

In [28]:
eigenvalues,eigenvectors=np.linalg.eig(B)

In [29]:
V=eigenvectors
VI=np.linalg.inv(V)
D=np.diag(eigenvalues)

In [30]:
eigenvalues

array([-1.52079729,  4.        , 10.52079729])

In [31]:
print(eigenvectors)

[[-0.74160799 -0.66666667  0.07465353]
 [-0.54849427  0.66666667  0.50468762]
 [ 0.38622743 -0.33333333  0.86006817]]


In [38]:
np.linalg.inv(eigenvectors)

array([[-0.74160799, -0.54849427,  0.38622743],
       [-0.66666667,  0.66666667, -0.33333333],
       [ 0.07465353,  0.50468762,  0.86006817]])

In [32]:
(V@D@VI).round()

array([[ 1., -2.,  2.],
       [-2.,  4.,  4.],
       [ 2.,  4.,  8.]])

In [33]:
B

array([[ 1, -2,  2],
       [-2,  4,  4],
       [ 2,  4,  8]])

In [35]:
B@np.array([-2,2,-1])

array([-8,  8, -4])

B Es simétrica, por lo tanto, se diagonaliza de manera real y por lo tango no hay valores imaginarios en los valores o vectores propios

In [48]:
C=np.array([[3,0,-1],
           [0,3,2],
           [0,0,-3]])

C

array([[ 3,  0, -1],
       [ 0,  3,  2],
       [ 0,  0, -3]])

In [49]:
eigenvalues,eigenvectors=np.linalg.eig(C)

In [50]:
eigenvalues

array([ 3.,  3., -3.])

In [51]:
eigenvectors

array([[ 1.        ,  0.        ,  0.15617376],
       [ 0.        ,  1.        , -0.31234752],
       [ 0.        ,  0.        ,  0.93704257]])

In [52]:
V=eigenvectors
VI=np.linalg.inv(V)
D=np.diag(eigenvalues)

In [55]:
VI

array([[ 1.        ,  0.        , -0.16666667],
       [ 0.        ,  1.        ,  0.33333333],
       [ 0.        ,  0.        ,  1.06718737]])

In [53]:
(V@D@VI).round()

array([[ 3.,  0., -1.],
       [ 0.,  3.,  2.],
       [ 0.,  0., -3.]])

In [54]:
C

array([[ 3,  0, -1],
       [ 0,  3,  2],
       [ 0,  0, -3]])

In [64]:
v=np.array([1,-2,5,7])
v

array([ 1, -2,  5,  7])

In [67]:
S=np.diag(v)
S

array([[ 1,  0,  0,  0],
       [ 0, -2,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0,  7]])

In [69]:
ST=np.transpose(S)
ST

array([[ 1,  0,  0,  0],
       [ 0, -2,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0,  7]])

In [70]:
S@ST

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 49]])

In [71]:
ST@S

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 25,  0],
       [ 0,  0,  0, 49]])