## Aproximación de valores propios 

En esta sección analizamos algunos métodos que se pueden utilizar para aproximar los valores propios de una matriz.A
. Aunque es posible encontrar los valores propios exactos para matrices pequeñas, el método no es práctico para matrices más grandes.

La mayoría de los libros de texto introductorios demuestran una forma directa de calcular los valores propios de unn×n
matrizA
calculando las raíces de un asociadon
Polinomio de grado, conocido como polinomio característico . Por ejemplo, supongamosA
es un2×2
matriz.

A=[acbd]

Los valores propios de A
son soluciones de la ecuación cuadráticaλ2−(a+d)λ+ad−bc=0
, que se puede escribir explícitamente en términos de a,b,c, y d usando la fórmula cuadrática. Los desafíos con matrices más grandes son que el polinomio es más difícil de construir y las raíces no se pueden encontrar fácilmente con una fórmula.

Los algoritmos que describimos en esta sección son métodos iterativos. Generan una secuencia de vectores.{X(1),X(2),X(3),...}
que se acerquen a un verdadero vector propio de la matriz bajo consideración. Luego se puede calcular una aproximación del valor propio correspondiente multiplicando el vector propio aproximado por A.







Método de potencia 

El primer algoritmo que presentamos para aproximar valores propios se conoce como Método de potencia . Este método genera una secuencia de vectores mediante multiplicación repetida de matrices. En condiciones adecuadas, la secuencia de vectores se acerca al vector propio asociado con el valor propio que es mayor en valor absoluto.

Para la explicación más simple, supongamos queA
es unn×n
matriz diagonalizable con vectores propios{V1,V2,...Vn}
, y esoλ1
es el valor propio deA
que es el mayor en valor absoluto. Para comenzar el método de potencia, elegimos cualquier vector distinto de cero y lo etiquetamosX(0)
. podemos expresarX(0)
 como una combinación lineal de los vectores propios ya que forman una base paraRn
.

X(0)=c1V1+c2V2+...cnVn
Ahora formamos una secuencia de vectores.X(1)
,X(2)
,X(3)
, …, configurandoX(m)=AX(m−1)
. Cada uno de estos vectores también se expresa fácilmente en términos de vectores propios.

X(1)=AX(0)X(2)=AX(1)X(m)=AX(m−1)====⋮==c1AV1+c2AV2+...cnAVnc1λ1V1+c2λ2V2+...cnλnVnc1λ1AV1+c2λ2AV2+...cnλnAVnc1λ21V1+c2λ22V2+...cnλ2nVnc1λm−11AV1+c2λm−12AV2+...cnλm−1nAVnc1λm1V1+c2λm2V2+...cnλmnVn
 
En la expresión paraX(m)
, entonces podemos factorizarλm1
para entender lo que sucede comom
se hace grande.

X(m)=λm1(c1V1+c2(λ2λ1)mV2+...cn(λnλ1)mVn)
Si|λ1|>|λi|
para todosi≠1
, entonces|λi/λ1|<1
y(λi/λ1)m
se acercará a cero comom
se hace grande. Esto significa que si multiplicamos repetidamente un vector por la matrizA
, eventualmente obtendremos un vector que está muy cerca de la dirección del vector propio que corresponde alλ1
.


In [2]:
import numpy as np
import laguide as lag

In [3]:
A = np.array([[-2, 6, 2, -8],[-6, 0, 12, 12],[-6, 0, 12, 12],[-10, 3, 7, 14]])
X = np.array([[1],[0],[0],[0]])

m = 0
while (m < 20):
    X = A@X
    X = X/lag.Magnitude(X)  ## Esta es una función para sacar la norma euclidiana de un vector
    m = m + 1
    
print(X)

[[ 1.57523994e-12]
 [-5.77350269e-01]
 [-5.77350269e-01]
 [-5.77350269e-01]]


El vector X resultante es el vector propio dominante de la matriz A, que representa la distribución estacionaria de un proceso de Markov asociado a la matriz A

In [4]:
A = np.array([[-2, 6, 2, -8],[-6, 0, 12, 12],[-6, 0, 12, 12],[-10, 3, 7, 14]])
X = np.array([[1],[0],[0],[0]])

m = 0
while (m < 20):
    X = A@X
    X = X/np.linalg.norm(X)  ### Esta es la norma Euclidiana
    m = m + 1
    
print(X)

[[ 1.57523994e-12]
 [-5.77350269e-01]
 [-5.77350269e-01]
 [-5.77350269e-01]]


Ahora si X es el vector propio de A con magnitud (distancia) unitaria, entonces|AX|=|λ1X|=|λ1. Por lo tanto podemos aproximarnos|λ1|con|AX|. Donde λ1 es el valor propio de A.

In [5]:
print(np.linalg.norm(A@X))

24.000000000020005


Parece que 24 es una estimación para λ1. Para determinar si nuestro cálculo es correcto, podemos comparar AX
con λ1X.

In [6]:
print(A@X - 24*X)

[[-4.09561274e-11]
 [-9.45021839e-12]
 [-9.45021839e-12]
 [-1.57509561e-11]]


De hecho la diferencia AX−24X es pequeño. Tenga en cuenta que en este caso, incluso podemos hacer el cálculo con la multiplicación de números enteros. Darse cuenta de X tiene 0 en la primera entrada y las demás entradas son iguales. Si configuramos estas entradas en 1, el resultado es fácil de calcular incluso sin la ayuda de la computadora. ( Recuerde que podemos cambiar la magnitud de un vector propio y sigue siendo un vector propio ) .

En la práctica, no sabemos cuántas iteraciones necesitamos realizar para obtener una buena aproximación del vector propio. En lugar de eso, deberíamos especificar una condición bajo la cual estaremos satisfechos con la aproximación y terminar la iteración. Por ejemplo, desde||AX(m)||≈λ1
yAX(m)≈λ1X(m)
podríamos requerir queAX(m)−||AX(m)||X(m)<ϵ
por un pequeño númeroϵ
conocido como tolerancia. Esta condición asegura queX(m)
funciona aproximadamente como un vector propio. También es mejor incluir en el código un límite en el número de iteraciones que se llevarán a cabo. Esto garantiza que el cálculo finalmente finalizará, incluso si aún no se ha logrado un resultado satisfactorio.

In [8]:
X = np.array([[1],[0],[0],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

## Calcular la diferencia en la condición de parada
## Asigne Y = AX para evitar calcular AX varias veces
Y = A@X
difference = Y - np.linalg.norm(Y)*X

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X = Y
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    Y = A@X
    difference = Y - np.linalg.norm(Y)*X
    
    m = m + 1
    
print("El vector propio es aproximadamente:")
print(X,'\n')
print("La magnitud del valor propio es aproximada.y:")
print(np.linalg.norm(Y),'\n')
print("La magnitud de la diferencia es:")
print(np.linalg.norm(difference))

El vector propio es aproximadamente:
[[ 1.65181395e-06]
 [-5.77350269e-01]
 [-5.77350269e-01]
 [-5.77350269e-01]] 

La magnitud del valor propio es aproximada.y:
24.000020980823063 

La magnitud de la diferencia es:
4.328470441185797e-05


Una condición más común que se requiere es que ||X(m)−X(m−1)||<ϵ para una tolerancia dada ϵ. Esta condición simplemente requiere que los vectores en la secuencia se acerquen entre sí, no que en realidad sean aproximados a un vector propio.

In [9]:
X = np.array([[1],[0],[0],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

difference = X

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = A@X
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1
    
print("Eigenvector is approximately:")
print(X,'\n')
print("Magnitude of the eigenvalue is approximately:")
print(np.linalg.norm(Y),'\n')
print("Magnitude of the difference is:")
print(np.linalg.norm(difference))

Eigenvector is approximately:
[[ 2.64294012e-05]
 [-5.77350269e-01]
 [-5.77350269e-01]
 [-5.77350269e-01]] 

Magnitude of the eigenvalue is approximately:
24.000020980823063 

Magnitude of the difference is:
8.434774776931515e-05


Si bien el Método Power es fácil de entender y aplicar, tiene desventajas. La desventaja más evidente es que el método sólo se aplica al valor propio más grande. Esto no supone un gran perjuicio, ya que las aplicaciones a menudo sólo requieren una aproximación del valor propio más grande. Además, como demostraremos a continuación, es posible modificar fácilmente el método para aproximar los otros valores propios. Una desventaja más importante es que la velocidad a la que converge la secuencia puede ser lenta en algunas circunstancias. Por ejemplo, podemos ver que si|λ1|
esta cerca de|λ2|
, entonces|λ1/λ2|m
se acerca a cero más lentamente a medida quem
se hace grande. El método de la potencia puede no converger en absoluto si|λ1|=|λ2|
, que ocurre siλ1=−λ2
, o siλ1
yλ2
son un par conjugado complejo. Además, el método puede funcionar mal si elV1
componente deX(0)
Es demasiado pequeño.



## Método de potencia inversa

El Método de la Potencia Inversa es una versión modificada del Método de la Potencia que nos permite aproximar valores propios que no son los más grandes . Todo lo que se necesita para realizar la modificación son dos hechos simples que relacionen los cambios en una matriz con los cambios en los valores propios de esa matriz. Supongamos queA
es invertiblen×n
matriz con valor propioλ
y vector propio correspondienteV
, de modo queAV=λV
. Si multiplicamos esta ecuación porA−1
, obtenemosV=λA−1V
, que luego se puede dividir porλ
para ilustrar el hecho útil

A−1V=1λV

Siλ
es un valor propio deA
, entoncesλ−1
es un valor propio deA−1
. Además, el vector propio deA
también es un vector propio deA−1
. El punto importante aquí es que siλn
es el valor propio más pequeño deA
, entoncesλ−1n
es el vector propio más grande deA−1
. Si queremos aproximar el valor propio más pequeño deA
, podemos simplemente aplicar el método de potencia aA−1
.

Demostramos el cálculo para lo siguiente3×3
matriz.

Nuevamente elegimos un arbitrario.X(0)
y generar una secuencia de vectores multiplicando porA−1
y escalar el resultado a la unidad de longitud.

X(m) = A−1X(m−1) / ||A−1X(m−1)||

In [29]:
X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

difference = X
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
A_inv = lag.Inverse(A)

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = A_inv@X
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1
    
print("El vector propio es aproximadamente:")
print(X,'\n')
print("La magnitud del valor propio de A inverso es aproximadamente:")
print(np.linalg.norm(A_inv@X),'\n')
print("La magnitud del valor propio de A es aproximadamente:")
print(np.linalg.norm(A@X),'\n')

El vector propio es aproximadamente:
[[-4.47193123e-01]
 [ 6.14168469e-05]
 [-8.94437425e-01]] 

La magnitud del valor propio de A inverso es aproximadamente:
0.3333371476391265 

La magnitud del valor propio de A es aproximadamente:
2.999931351114087 



En nuestra discusión sobre matrices inversas notamos que la construcción de una matriz inversa es bastante costosa ya que requiere la solución den
sistemas de tamañon×n
. Una alternativa a la construcción.A−1
y calculando el X(m)=A−1X(m−1)
es resolver el sistemaAX(m)=X(m−1)
para obtenerX(m)
. Esto significa que resolvemos unon×n
sistema para cada iteración. Esto parece requerir más trabajo que la construcción deA−1
, pero en realidad es menor ya que cada sistema involucra la misma matriz de coeficientes. Por lo tanto, podemos ahorrar mucho trabajo realizando la eliminación sólo una vez y almacenando el resultado en unLU
factorización. con la matrizA
factorizado, cada sistemaAX(m)=X(m−1)
Solo requiere una sustitución hacia adelante y una sustitución hacia atrás.

In [30]:
import scipy.linalg as sla

X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

difference = X
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
LU_factorization = sla.lu_factor(A)

while (m < MAX_ITERATIONS and lag.Magnitude(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)
    X = X/lag.Magnitude(X)
    difference = X - X_previous
    m = m + 1
  
print("Eigenvector is approximately:")
print(X,'\n')
print("Magnitude of the eigenvalue of A inverse is approximately:")
print(lag.Magnitude(sla.lu_solve(LU_factorization,X)),'\n')
print("Magnitude of the eigenvalue of A is approximately:")
print(lag.Magnitude(A@X),'\n')

Eigenvector is approximately:
[[-4.47193123e-01]
 [ 6.14168469e-05]
 [-8.94437425e-01]] 

Magnitude of the eigenvalue of A inverse is approximately:
0.3333371476391265 

Magnitude of the eigenvalue of A is approximately:
2.999931351114087 

