In [30]:
import numpy as np
import scipy.linalg as sla
from scipy.linalg import eig

## Problema 1.a 

- Utilice el método de la potencia para aproximar el valor propio más grande λ1. Verifique que el valor exacto de λ1 es 12 

R/


In [25]:
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

## Calcular la diferencia en la condición de parada
## Asigne Y = AX para evitar el calculo de AX varias veces
Y = A@X
difference = Y - np.linalg.norm(Y)*X

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X = Y
    X = X/np.linalg.norm(X)

    ## Calcular la diferencia en la condición de parada
    Y = A@X
    difference = Y - np.linalg.norm(Y)*X
    
    m = m + 1
    
print("El vector propio es aproximadamente:")
print(X,'\n')
print("La magnitud del valor propio es aproximadamente:")
print(np.linalg.norm(Y),'\n')

El vector propio es aproximadamente:
[[-7.07103544e-01]
 [ 9.71065612e-06]
 [ 7.07110018e-01]] 

La magnitud del valor propio es aproximadamente:
12.000013732475342 



Ahora para validar que nuestro calculo es correcto vamos a comparar AX con λ1X. Siendo λ1 = valor propio

In [14]:
print(A@X - 12.000013732475342 *X)

[[-1.94216123e-05]
 [-5.82640701e-05]
 [-1.94208788e-05]]


In [15]:
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
lamda = np.array([[-7.07103544e-01], [9.71065612e-06],[7.07110018e-01] ])
Verificacion = A@lamda
Verificacion

array([[-8.48527166e+00],
       [ 5.82639367e-05],
       [ 8.48531050e+00]])

## Problema 1.b 

- Aplique el método de potencia inversa con un desplazamiento de μ=10. Explique por qué los resultados difieren de los del ejemplo.

R/

In [16]:
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100
difference = X

A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
I = np.eye(3) # Se crea una matriz de identidad 3x3
mu = 10
Ajuste_A = A-mu*I
LU_factorization = sla.lu_factor(Ajuste_A)  ## Se utiliza para calcular la factorización LU de A con un pivoteo parcial

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)  # Se soluciona el sistema de ecuaciones tomando la matriz original y la factorización LU
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1

print("El vector propio es aproximadamente:")
print(X,'\n')
print("La magnitud del valor propio es aproximadamente:")
print(np.linalg.norm(A@X))

El vector propio es aproximadamente:
[[-7.07113254e-01]
 [-1.94211789e-05]
 [ 7.07100308e-01]] 

La magnitud del valor propio es aproximadamente:
11.999972530202639


In [17]:
print(A@X - 11.999972530202639 *X)

[[3.88364103e-05]
 [1.16526540e-04]
 [3.88393440e-05]]


El resultado da muy diferente al ejemplo, ya que el valor propio más grande es 12 y nosotros estamos cogiendo μ = 10, muy cercano al vector propio más grande. En el ejemplo se cogio μ = 7, un valor que esta más central entre el valor propio más grande y el vector propio más pequeño.

## Problema 1.c 

- Aplique el método de potencia inversa con un desplazamiento de μ=7.5 y el vector inicial que se muestra a continuación. Explique por qué la secuencia de vectores se aproxima al vector propio correspondiente a λ1

R/

In [20]:
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
X = np.array([[1],[0],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100
difference = X

A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
I = np.eye(3)
mu = 7.5
Shifted_A = A-mu*I
LU_factorization = sla.lu_factor(Shifted_A)

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1

print("Eigenvector is approximately:")
print(X,'\n')
print("Eigenvalue of A is approximately:")
print(np.linalg.norm(A@X))

Eigenvector is approximately:
[[ 1.]
 [-0.]
 [-0.]] 

Eigenvalue of A is approximately:
10.816653826391969


El método de la potencia inversa con un desplazamiento de U encuentra el valor propio más cercano a U. A tiene tres valores propios, a saber, 3, 6 y 12, de los cuales 10 es el más cercano a 12 y 7,5 es el más cercano a 6. Es por eso que cuando usamos μ = 7,5 en el ejemplo obtuvimos el valor propio 6, pero cuando usamos μ =7.5 obtuvimos el valor propio 12

## Problema 2.a 

- Aplicar el método de potencia y el método de potencia inversa con desplazamientos para aproximar todos los valores propios de la matriz B( Tenga en cuenta que uno de los valores propios de esta matriz es negativo ).

R/

Aplicamos el metodo de potencia 

In [27]:
A = np.array([[-2,-18,-6],[-11,3,11],[-27,15,31]])
X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

## Calcular la diferencia en la condición de parada
## Asigne Y = AX para evitar el calculo de AX varias veces
Y = A@X
difference = Y - np.linalg.norm(Y)*X

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X = Y
    X = X/np.linalg.norm(X)

    ## Calcular la diferencia en la condición de parada
    Y = A@X
    difference = Y - np.linalg.norm(Y)*X
    
    m = m + 1
    
print("El vector propio es aproximadamente:")
print(X,'\n')
print("La magnitud del valor propio es aproximadamente:")
print(np.linalg.norm(Y),'\n')

El vector propio es aproximadamente:
[[-0.24626613]
 [ 0.31622748]
 [ 0.9161622 ]] 

La magnitud del valor propio es aproximadamente:
43.435119198306694 



Aplicamos el metodo de potencia inversa 

In [28]:
A = np.array([[-2,-18,-6],[-11,3,11],[-27,15,31]])
X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

difference = X
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
LU_factorization = sla.lu_factor(A)

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)
    X = X/np.linalg.norm(X)
    difference = X - X_previous
    m = m + 1
  
print("Eigenvector is approximately:")
print(X,'\n')
print("Magnitude of the eigenvalue of A inverse is approximately:")
print(np.linalg.norm(sla.lu_solve(LU_factorization,X)),'\n')
print("Magnitude of the eigenvalue of A is approximately:")
print(np.linalg.norm(A@X),'\n')

Eigenvector is approximately:
[[-4.47193123e-01]
 [ 6.14168469e-05]
 [-8.94437425e-01]] 

Magnitude of the eigenvalue of A inverse is approximately:
0.3333371476391265 

Magnitude of the eigenvalue of A is approximately:
2.999931351114087 



Aplicamos el metodo de potencia inversa con desplazaminto, escogiendo μ = 23

In [29]:
B = np.array([[-2,-18,-6],[-11,3,11],[-27,15,31]])
X = np.array([[0],[1],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100
difference = X

B = np.array([[-2,-18,-6],[-11,3,11],[-27,15,31]])
I = np.eye(3)
mu = 23
Shifted_B = B-mu*I
LU_factorization = sla.lu_factor(Shifted_B)

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1

print("Eigenvector is approximately:")
print(X,'\n')
print("Eigenvalue of B is approximately:")
print(np.linalg.norm(B@X))

Eigenvector is approximately:
[[-0.24631364]
 [ 0.31625724]
 [ 0.91613915]] 

Eigenvalue of B is approximately:
43.43623681272888


## Problema 2.b

Verifique sus resultados usando el eigFunción en SciPy.

R/

In [31]:
B = np.array([[-2,-18,-6],[-11,3,11],[-27,15,31]])

eigenvalues, eigenvectors = eig(B)

print("Valores propios:")
print(eigenvalues)

print("Vectores propios:")
print(eigenvectors)

Valores propios:
[ 43.43509994+0.j -11.71802235+0.j   0.28292241+0.j]
Vectores propios:
[[-0.24626499  0.84814429  0.63062728]
 [ 0.31622777  0.31622777 -0.31622777]
 [ 0.91616241  0.4250309   0.70873777]]


Como se puede observar, los resultados dieron igual, utilizando el metodo de potencia, el metodo de potencia inversa y el metodo de potencia inversa con desplazamiento VS la función eig de Scipy