In [25]:
import numpy as np
import laguide as lag
import scipy.linalg as sla

## Problema 1.a 

- Utilice el método de la potencia para aproximar el valor propio más grande λ1. Verifique que el valor exacto de λ1 es 12 

R/


In [26]:
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
X = np.array([[1],[0],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100

## Calcular la diferencia en la condición de parada
## Asigne Y = AX para evitar el calculo de AX varias veces
Y = A@X
difference = Y - np.linalg.norm(Y)*X

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X = Y
    X = X/np.linalg.norm(X)

    ## Calcular la diferencia en la condición de parada
    Y = A@X
    difference = Y - np.linalg.norm(Y)*X
    
    m = m + 1
    
print("El vector propio es aproximadamente:")
print(X,'\n')
print("La magnitud del valor propio es aproximadamente:")
print(np.linalg.norm(Y),'\n')

El vector propio es aproximadamente:
[[ 0.7071088 ]
 [ 0.        ]
 [-0.70710476]] 

La magnitud del valor propio es aproximadamente:
12.000008583030988 



Ahora para validar que nuestro calculo es correcto vamos a comparar AX con λ1X. Siendo λ1 = valor propio

In [20]:
print(A@X - 12.000013732475342 *X)

[[-2.18486582e-05]
 [ 0.00000000e+00]
 [-1.45663092e-05]]


In [21]:
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
lamda = np.array([[-7.07103544e-01], [9.71065612e-06],[7.07110018e-01] ])
Verificacion = A@lamda
Verificacion

array([[-8.48527166e+00],
       [ 5.82639367e-05],
       [ 8.48531050e+00]])

## Problema 1.b 

- Aplique el método de potencia inversa con un desplazamiento de μ=10. Explique por qué los resultados difieren de los del ejemplo.

R/

In [33]:
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
X = np.array([[1],[0],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100
difference = X

A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
I = np.eye(3) # Se crea una matriz de identidad 3x3
mu = 10
Ajuste_A = A-mu*I
LU_factorization = sla.lu_factor(Ajuste_A)  ## Se utiliza para calcular la factorización LU de A con un pivoteo parcial

while (m < MAX_ITERATIONS and np.linalg.norm(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)  # Se soluciona el sistema de ecuaciones tomando la matriz original y la factorización LU
    X = X/np.linalg.norm(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1

print("El vector propio es aproximadamente:")
print(X,'\n')
print("La magnitud del valor propio es aproximadamente:")
print(np.linalg.norm(A@X))

El vector propio es aproximadamente:
[[ 0.70710005]
 [-0.        ]
 [-0.70711351]] 

La magnitud del valor propio es aproximadamente:
11.99997145194728


In [30]:
MU = mu *I
MU = A - MU
MU

array([[-1., -1., -3.],
       [ 0., -4.,  0.],
       [-6.,  3., -4.]])

## Problema 1.c 

- Aplique el método de potencia inversa con un desplazamiento de μ=7.5 y el vector inicial que se muestra a continuación. Explique por qué la secuencia de vectores se aproxima al vector propio correspondiente a λ1

R/

In [10]:
A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
X = np.array([[1],[0],[0]])

m = 0
tolerance = 0.0001
MAX_ITERATIONS = 100
difference = X

A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
I = np.eye(3)
mu = 7.5
Shifted_A = A-mu*I
LU_factorization = sla.lu_factor(Shifted_A)

while (m < MAX_ITERATIONS and lag.Magnitude(difference) > tolerance):
    X_previous = X
    X = sla.lu_solve(LU_factorization,X)
    X = X/lag.Magnitude(X)

    ## Compute difference in stopping condition
    difference = X - X_previous
    
    m = m + 1

print("Eigenvector is approximately:")
print(X,'\n')
print("Eigenvalue of A is approximately:")
print(lag.Magnitude(A@X))

Eigenvector is approximately:
[[ 1.]
 [-0.]
 [-0.]] 

Eigenvalue of A is approximately:
10.816653826391969


El método de la potencia inversa con un desplazamiento de U encuentra el valor propio más cercano a U. A tiene tres valores propios, a saber, 3, 6 y 12, de los cuales 10 es el más cercano a 12 y 7,5 es el más cercano a 6. Es por eso que cuando usamos LAMDA = 7,5 en el ejemplo obtuvimos el valor propio 6, pero cuando usamos LAMDA =7.5 obtuvimos el valor propio 12

## Problema 2.a 

- Aplicar el método de potencia y el método de potencia inversa con desplazamientos para aproximar todos los valores propios de la matriz B( Tenga en cuenta que uno de los valores propios de esta matriz es negativo ).